image: docker:latest


build:
  only:
  - master
  image: docker:latest
  services:
  - docker:dind
  before_script:
  - echo "Lets build"
  script:
  #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.booli.se:4567
  - docker build .
#  - docker-compose push
